FROM ubuntu:20.04 as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    autoconf \
    git \
    wget \
    python3 \
    build-essential \
    clang bison flex \
	libreadline-dev \
    gawk \
    tcl-dev \
    libffi-dev \
    git \
	graphviz \
    xdot \
    pkg-config \
    libboost-system-dev \
	libboost-python-dev \
    libboost-filesystem-dev \
    zlib1g-dev \
    clang bison \
    flex \
    libreadline-dev \
    gawk \
    tcl-dev \
    libffi-dev \
    mercurial graphviz \
    xdot \
    pkg-config \
    libftdi-dev \
    qtbase5-dev \
    qtchooser \
    qt5-qmake \
    qtbase5-dev-tools \
    python3-dev \
    libboost-all-dev \
    cmake \
    libeigen3-dev

RUN git clone https://github.com/YosysHQ/yosys.git 
RUN cd yosys; make; make install


RUN git clone https://github.com/YosysHQ/icestorm.git icestorm 
RUN cd icestorm; make -j$(nproc); make install

RUN apt -y purge cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4.tar.gz
RUN tar zxvf cmake-3.13.4.tar.gz
RUN cd cmake-3.13.4; ./bootstrap ;make ;make install

RUN git clone https://github.com/YosysHQ/nextpnr nextpnr 
RUN cd nextpnr; cmake -DARCH=ice40 -DCMAKE_INSTALL_PREFIX=/usr/local; make -j$(nproc); make install

RUN apt-get update && apt-get install -y \
    autoconf automake autotools-dev curl libmpc-dev \
        libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo \
    gperf libtool patchutils bc zlib1g-dev git libexpat1-dev

RUN mkdir /opt/riscv32i

RUN git clone https://github.com/riscv/riscv-gnu-toolchain riscv-gnu-toolchain-rv32i
RUN cd riscv-gnu-toolchain-rv32i; git submodule update --init --recursive
RUN cd riscv-gnu-toolchain-rv32i; mkdir build; cd build;  ../configure --with-arch=rv32i --prefix=/opt/riscv32i; make -j$(nproc)

ENV PATH="$PATH:/opt/riscv32i/bin"



