FROM ubuntu:latest as builder

RUN apt-get update && apt-get install -y \
    build-essential \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    autoconf \
    git \
    wget \
    python3

RUN git clone https://github.com/Z3Prover/z3.git
WORKDIR /z3
RUN python3 scripts/mk_make.py
RUN cd build; make

