FROM archfx/rvutils:latest as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y  autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev \
                 gawk build-essential bison flex texinfo gperf libtool patchutils bc \
                 zlib1g-dev libexpat-dev python3 pkg-config libglib2.0-dev libpixman-1-dev libattr1-dev libcap-ng-dev

RUN git clone https://github.com/qemu/qemu; cd qemu; git checkout v5.0.0;  \   
	./configure \
		--disable-gtk \
		--disable-opengl \
		--disable-sdl \
		--disable-vnc \
		--disable-vte \
		--enable-kvm \
		--enable-virtfs \
		--target-list=riscv64-softmmu,riscv32-softmmu; make -j $(nproc); make install 
RUN rm -rfv qemu

