FROM ubuntu:20.04 as builder

ARG DEBIAN_FRONTEND=noninteractive

# RUN apt-get update && apt-get install -y \
#     autoconf automake autotools-dev curl libmpc-dev \
#         libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo \
#     gperf libtool patchutils bc zlib1g-dev git libexpat1-dev 

RUN apt-get update && apt-get install -y \
        git wget iverilog
RUN mkdir /opt/riscv
RUN wget https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv64imc-3.0.0/riscv64-unknown-elf.gcc-12.1.0.tar.gz
RUN tar -xzf riscv64-unknown-elf.gcc-12.1.0.tar.gz -C /opt/riscv/

# RUN git clone https://github.com/riscv/riscv-gnu-toolchain riscv-gnu-toolchain-rv32i
# RUN cd riscv-gnu-toolchain-rv32i; git submodule update --init --recursive
# RUN cd riscv-gnu-toolchain-rv32i; mkdir build; cd build;  ../configure --with-arch=rv32i --prefix=/opt/riscv32i; make -j$(nproc)

ENV PATH="$PATH:/opt/riscv/bin"

RUN rm -r riscv64-unknown-elf.gcc-12.1.0.tar.gz