FROM ubuntu:latest as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    autoconf \
    git \
    wget \
    python3 \
    python3-pip
    
RUN wget -O archfx https://raw.githubusercontent.com/Archfx/archfx/main/images/graffiti.txt;  cat archfx >> ~/.bashrc ; rm archfx
RUN sed -i 's/# force_color_prompt=yes/force_color_prompt=yes/' ~/.bashrc