FROM ubuntu:latest as builder

ARG DEBIAN_FRONTEND=noninteractive



RUN apt-get update && apt-get install -y \
    build-essential \
    autoconf \
    git \
    wget \
    python3 \
    python3-pip
    



