FROM ubuntu:18.04 as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf libxml2 \
    lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev imagemagick git \
    lunzip lzop schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk python perl  \
    xmlstarlet virtualenv xz-utils rr jq libncurses5 pngcrush lib32ncurses5-dev git-lfs libxml2 \
    openjdk-11-jdk-headless

RUN PATH=~/bin:$PATH ; curl https://storage.googleapis.com/git-repo-downloads/repo > /bin/repo; chmod a+x /bin/repo