FROM archfx/ubuntu:latest as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    autoconf \
    git \
    wget \
    python3 \
    build-essential \
    clang bison flex \
	libreadline-dev \
    gawk \
    tcl-dev \
    libffi-dev \
    git \
	graphviz \
    xdot \
    pkg-config \
    libboost-system-dev \
	libboost-python-dev \
    libboost-filesystem-dev \
    zlib1g-dev \
    clang bison \
    flex \
    libreadline-dev \
    gawk \
    tcl-dev \
    libffi-dev \
    mercurial graphviz \
    xdot \
    pkg-config \
    libftdi-dev \
    qtbase5-dev \
    qtchooser \
    qt5-qmake \
    qtbase5-dev-tools \
    python3-dev \
    libboost-all-dev \
    cmake \
    libeigen3-dev

RUN git clone https://github.com/YosysHQ/yosys.git 
RUN cd yosys; make; make install


RUN git clone https://github.com/YosysHQ/icestorm.git icestorm 
RUN cd icestorm; make -j$(nproc); make install

RUN apt -y purge cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4.tar.gz
RUN tar zxvf cmake-3.13.4.tar.gz
RUN cd cmake-3.13.4; ./bootstrap ;make ;make install

RUN git clone https://github.com/YosysHQ/nextpnr nextpnr 
RUN cd nextpnr; cmake . -DARCH=ice40 -DICESTORM_INSTALL_PREFIX=/usr/local; make -j$(nproc); make install


RUN rm -r yosys
RUN rm -r icestorm
RUN rm -r cmake-3.13.4.tar.gz
RUN rm -r cmake-3.13.4
RUN rm -r nextpnr

