FROM ubuntu:latest as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    autoconf \
    git \
    wget \
    python3 \
    racket \
    libssl-dev

 
# RUN git clone https://github.com/Z3Prover/z3.git
# WORKDIR /z3
# RUN python3 scripts/mk_make.py
# RUN cd build; make
# RUN  yes | raco pkg install racket-doc
RUN  yes | raco pkg install rosette ; exit 0
