FROM ubuntu:latest as builder

ARG DEBIAN_FRONTEND=noninteractive



RUN apt-get update && apt-get install -y \
    build-essential \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    autoconf \
    git \
    wget \
    python3 \
    racket \
    libssl-dev \
    libzmq5 \
    python3-pip
    
 
RUN pip3 install notebook

RUN raco setup --doc-index --force-user-docs

RUN git clone https://github.com/emina/rosette.git
WORKDIR /rosette
RUN yes | raco pkg install 

RUN git clone https://github.com/anishathalye/rtlv
WORKDIR /rtlv
RUN yes | raco pkg install 

RUN yes | raco pkg install iracket

RUN yes | raco iracket install 

RUN sed -i 's/"--",/"--","-t",/g' /root/.local/share/jupyter/kernels/racket/kernel.json



