FROM ubuntu:18.04 as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
    lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip libssl-dev libxml-simple-perl \
    libc++1 libc++-dev python bc filter


RUN mkdir ~/bin; PATH=~/bin:$PATH ;curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo; chmod a+x ~/bin/repo

RUN mkdir ~/repo; cd ~/repo; repo init -u https://github.com/microsoft/surface-duo-oss-kernel.manifest -b surfaceduo/10/2020.618.244; repo sync

# RUN mkdir -p ~/repo/proprietary/llvm-arm-toolchain-ship/8.0;