FROM archfx/rvutils as builder
    
RUN pip3 install notebook

RUN apt-get update && apt-get install -y \
	curl
	
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y 

RUN source "$HOME/.cargo/env"


