FROM ubuntu:20.04 as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    autoconf automake autotools-dev curl libmpc-dev \
        libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo \
    gperf libtool patchutils bc zlib1g-dev git libexpat1-dev
    
RUN mkdir /opt/riscv32i

RUN git clone https://github.com/riscv/riscv-gnu-toolchain riscv-gnu-toolchain-rv32i
RUN cd riscv-gnu-toolchain-rv32i; git submodule update --init --recursive
RUN cd riscv-gnu-toolchain-rv32i; mkdir build; cd build;  ../configure --with-arch=rv32i --prefix=/opt/riscv32i; make -j$(nproc)

ENV PATH="$PATH:/opt/riscv32i/bin"

RUN rm -r riscv-gnu-toolchain-rv32i # clean downloaded files