FROM archfx/ubuntu:latest as builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
        git wget iverilog libmpc-dev verilator pip
RUN mkdir /opt/riscv

RUN wget https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv64imc-3.0.0/riscv64-unknown-elf.gcc-12.1.0.tar.gz
RUN tar -xzf riscv64-unknown-elf.gcc-12.1.0.tar.gz -C /opt/riscv/

RUN wget https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz
RUN tar -xzf riscv32-unknown-elf.gcc-12.1.0.tar.gz -C /opt/riscv/


ENV PATH="$PATH:/opt/riscv/bin"

RUN rm -r riscv64-unknown-elf.gcc-12.1.0.tar.gz
RUN rm -r riscv32-unknown-elf.gcc-12.1.0.tar.gz

RUN pip install matplotlib
