name: ice40tv80

on:
  push:
    paths:
    - 'ice40tv80/dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: set release date
      run: | 
        echo "DATE=$(date +"%Y%m%d")" >> ${GITHUB_ENV}
    - uses: actions/checkout@v3
      name: Check out code
    # - uses: actions/checkout@v3
    # - name: RV32I latest - Build the Docker image
    #   run: docker build . --file RV32I/dockerfile --tag archfx/rv32i:latest
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: archfx/ice40tv80
        tags: latest, $DATE
        registry: docker.io
        dockerfile: ice40tv80/dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
