name: Docker Image CI

on:
  push:
    paths:
    - 'RV32I/dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file RV32I/dockerfile --tag archfx/rv32i:latest
