name: android-latest

on:
  push:
    paths:
    - 'android/dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code
    # - uses: actions/checkout@v3
    # - name: RV32I latest - Build the Docker image
    #   run: docker build . --file RV32I/dockerfile --tag archfx/rv32i:latest
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: archfx/android
        tags: latest
        registry: docker.io
        dockerfile: android/dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
