name: LinuxDev

on:
  push:
    paths:
    - 'LinuxDev/dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code
 
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: archfx/linuxdev
        tags: v1, latest
        registry: docker.io
        dockerfile: LinuxDev/dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
